import assert from 'node:assert/strict'
import fs from 'node:fs'
import {
  STUDIO_V2_MACBOOK_SITE_CONFIG,
  STUDIO_V2_MACBOOK_SITE_PHASES,
  STUDIO_V2_MACBOOK_SITE_STATES,
  studioV2MacbookSiteCanOpen,
  studioV2MacbookSiteCanTransition,
  studioV2MacbookSiteLocksStudio,
} from './macbook-site/studioV2MacbookPortal.js'

assert.deepEqual(Object.values(STUDIO_V2_MACBOOK_SITE_STATES), ['CLOSED', 'OPENING', 'OPEN', 'CLOSING'])
assert.equal(STUDIO_V2_MACBOOK_SITE_PHASES.LAUNCHING, 'MACBOOK_CHROME_LAUNCHING')
assert.equal(STUDIO_V2_MACBOOK_SITE_PHASES.ENTERING, 'MACBOOK_SITE_TRANSITION_IN')
assert.equal(STUDIO_V2_MACBOOK_SITE_PHASES.SITE, 'MACBOOK_SITE_MODE')
assert.equal(STUDIO_V2_MACBOOK_SITE_PHASES.EXIT_DARKEN, 'MACBOOK_SITE_EXIT_DARKEN')
assert.equal(STUDIO_V2_MACBOOK_SITE_PHASES.EXIT_COVER, 'MACBOOK_SITE_EXIT_COVER')
assert.equal(STUDIO_V2_MACBOOK_SITE_PHASES.EXIT_HOLD, 'MACBOOK_SITE_EXIT_HOLD')
assert.equal(STUDIO_V2_MACBOOK_SITE_PHASES.EXIT_REVEAL, 'MACBOOK_SITE_EXIT_REVEAL')
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.defaultLaunchDurationMs >= 120)
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.defaultLaunchDurationMs <= 180)
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.transitionDurationMs >= 220)
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.transitionDurationMs <= 320)
assert.equal(STUDIO_V2_MACBOOK_SITE_CONFIG.exitDarkenDurationMs, 120)
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.exitOcclusionHoldMs >= 50)
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.exitOcclusionHoldMs <= 80)
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.exitRevealDurationMs >= 140)
assert.ok(STUDIO_V2_MACBOOK_SITE_CONFIG.exitRevealDurationMs <= 170)
assert.equal(studioV2MacbookSiteCanOpen('MACBOOK_FOCUS', 'CLOSED'), true)
assert.equal(studioV2MacbookSiteCanOpen('TABLE_FREE_ORBIT', 'CLOSED'), false)
assert.equal(studioV2MacbookSiteCanOpen('MACBOOK_FOCUS', 'OPEN'), false)
assert.equal(studioV2MacbookSiteLocksStudio('CLOSED'), false)
assert.equal(studioV2MacbookSiteLocksStudio('OPENING'), true)
assert.equal(studioV2MacbookSiteLocksStudio('OPEN'), true)
assert.equal(studioV2MacbookSiteLocksStudio('CLOSING'), true)
assert.equal(studioV2MacbookSiteCanTransition('CLOSED', 'OPENING'), true)
assert.equal(studioV2MacbookSiteCanTransition('OPENING', 'OPEN'), true)
assert.equal(studioV2MacbookSiteCanTransition('OPEN', 'CLOSING'), true)
assert.equal(studioV2MacbookSiteCanTransition('CLOSING', 'CLOSED'), true)
assert.equal(studioV2MacbookSiteCanTransition('CLOSING', 'OPENING'), false)

const portal = fs.readFileSync('src/studio-v2/macbook-site/MacbookSitePortal.jsx', 'utf8')
const app = fs.readFileSync('src/App.jsx', 'utf8')
const focus = fs.readFileSync('src/studio-v2/studioV2MacbookFocus.js', 'utf8')
const scene = fs.readFileSync('src/studio-v2/createStudioV2Scene.js', 'utf8')
const materials = fs.readFileSync('src/studio-v2/studioV2PlacedObjects.js', 'utf8')
const styles = fs.readFileSync('src/studio-v2/studio-v2.css', 'utf8')
const home = fs.readFileSync('src/components/HomeTransitionShell.jsx', 'utf8')
const chapters = fs.readFileSync('src/components/TransitionChapterNavigation.jsx', 'utf8')
const footprints = fs.readFileSync('src/sections/FootprintsSection.jsx', 'utf8')
const footprintsStyles = fs.readFileSync('src/styles/footprints.css', 'utf8')

assert.match(portal, /HomeTransitionShell releaseScope="v0\.9" scrollContainerRef=\{scrollContainerRef\}/)
assert.doesNotMatch(portal, /requestIdleCallback/)
assert.match(portal, /loadHomeModule\(\)/)
assert.match(portal, /subscribeMacbookFocus/)
assert.match(portal, /MACBOOK_FOCUS_TRANSITION/)
assert.match(portal, /setSiteMounted\(true\)/)
assert.match(portal, /MACBOOK_SITE_STATES\.OPENING/)
assert.match(portal, /MACBOOK_SITE_STATES\.CLOSING/)
assert.match(portal, /MACBOOK_SITE_PHASES\.LAUNCHING/)
assert.match(portal, /MACBOOK_SITE_PHASES\.EXIT_REVEAL/)
assert.match(portal, /data-scroll-owner="MACBOOK_SITE_MODE"/)
assert.match(portal, /savedScrollTopRef\.current/)
assert.match(portal, /event\.key !== 'Escape'/)
assert.match(portal, /← STUDIO/)
assert.match(portal, /macbook-site-portal__exit-veil/)
assert.match(portal, /runtime\?\.setMacbookSiteState\?\.\(next\)/)
assert.doesNotMatch(portal, /pendingOpenRef|setMacbookSiteMode|CanQueueReopen/)
assert.equal((portal.match(/window\.addEventListener\('keydown'/g) ?? []).length, 1)
assert.equal((portal.match(/window\.removeEventListener\('keydown'/g) ?? []).length, 1)
assert.match(portal, /clearScheduled\(\)[\s\S]*STUDIO_V2_MACBOOK_SITE_STATES\.OPENING/)
assert.match(portal, /clearScheduled\(\)[\s\S]*STUDIO_V2_MACBOOK_SITE_STATES\.CLOSING/)
assert.doesNotMatch(portal, /getMacbookPortalProjection|getMacbookDisplayProjection|portal__proxy/)
assert.match(home, /container: scrollContainerRef/)
assert.match(app, /pathname === '' \|\| pathname === '\/studio-v2-import-test'/)
assert.match(home, /releaseScope = 'full'/)
assert.match(home, /showProjects=\{includeProjects\}/)
assert.match(home, /visibleChapterIds=\{includeProjects \? undefined : v09ChapterIds\}/)
assert.match(chapters, /chapters\.filter\(\(chapter\) => visibleChapterIds\.includes\(chapter\.id\)\)/)
assert.match(footprints, /\{showProjects && \(/)
assert.match(footprintsStyles, /\.home-transition-shell--v0-9 \{[\s\S]*height: 490svh/)

assert.match(focus, /StudioV2MacbookChromeDockIcon/)
assert.match(focus, /MACBOOK_CHROME_DOCK_TARGET/)
assert.match(focus, /chromeDockCenterX: 0\.693/)
assert.match(focus, /chromeDockCenterY: 0\.875/)
assert.match(focus, /chromeIconSize: 0\.022/)
assert.match(focus, /chromeHoverScale: 1\.06/)
assert.match(focus, /chromeLaunchDurationMs: 160/)
assert.match(focus, /opacity: 1/)
assert.match(focus, /new THREE\.Mesh\(iconGeometry\.clone\(\), hitMaterial\)/)
assert.match(focus, /chromeDock\.hitTarget\.scale\.setScalar\(chromeScale\)/)
assert.doesNotMatch(focus, /size: 0\.055/)
assert.match(focus, /downOnChrome/)
assert.match(focus, /requestPortalOpen\(event\.pointerType/)
assert.match(focus, /domElement\.style\.cursor = chromeHovered \? 'pointer' : ''/)
assert.match(scene, /macbookFocus\?\.update\(time\)/)
assert.match(scene, /subscribeMacbookPortalOpenRequest/)
assert.match(scene, /getMacbookChromeProjection/)
assert.match(scene, /studioV2MacbookSiteLocksStudio\(macbookSiteState\)/)
assert.match(scene, /renderer\.domElement\.style\.pointerEvents = locked \? 'none' : ''/)
assert.match(scene, /setMacbookSiteState\(nextState\)/)
assert.doesNotMatch(scene, /setMacbookSiteMode\(enabled\)/)
assert.doesNotMatch(scene, /createStudioV2MacbookScreenPreview|getMacbookPortalProjection/)

assert.match(materials, /id: 'macbook-display-glass'[\s\S]*clearcoat: 0\.08/)
assert.match(materials, /id: 'macbook-display-glass'[\s\S]*envMapIntensity: 0\.16/)
assert.match(materials, /id: 'macbook-display-glass'[\s\S]*roughness: 0\.38/)
assert.match(styles, /MACBOOK_SITE_TRANSITION_IN/)
assert.match(styles, /data-macbook-site-phase='MACBOOK_SITE_TRANSITION_IN'/)
assert.match(styles, /opacity 280ms ease-in-out/)
assert.match(styles, /MACBOOK_SITE_EXIT_DARKEN[\s\S]*brightness\(0\.72\)/)
assert.match(styles, /MACBOOK_SITE_EXIT_REVEAL[\s\S]*macbook-site-exit-reveal-duration/)
assert.doesNotMatch(styles, /MACBOOK_SITE_TRANSITION_OUT/)
assert.doesNotMatch(styles, /macbook-portal-left|macbook-portal-scale|macbook-site-portal__proxy/)
assert.equal(fs.existsSync('src/studio-v2/studioV2MacbookScreenPreview.js'), false)
assert.equal(fs.existsSync('public/images/studio-v2/macbook-home-preview.jpg'), false)

console.log('Studio V2 Mac desktop, Chrome trigger, crossfade, input lock, and scroll smoke passed.')
